#!/usr/bin/env bash

GBW_PARAMS_GIT_CONFIG_KEY_ROOT="git-bash-workflow"
GBW_PARAMS_GIT_CONFIG_KEY_PROMPT_ACTIVE="$GBW_PARAMS_GIT_CONFIG_KEY_ROOT.prompt"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES_ACTIVE="$GBW_PARAMS_GIT_CONFIG_KEY_ROOT.gitaliases"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_ACTIVE="$GBW_PARAMS_GIT_CONFIG_KEY_ROOT.githooks"
GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW_ACTIVE="$GBW_PARAMS_GIT_CONFIG_KEY_ROOT.workflow"
GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES_ACTIVE="$GBW_PARAMS_GIT_CONFIG_KEY_ROOT.bashaliases"

GBW_PARAMS_GIT_ALIAS_DIFF_FILE="$GBW_PARAMS_ROOT/src/git/alias/git.alias.diff.sh"
GBW_PARAMS_GIT_ALIAS_COMMIT_FILE="$GBW_PARAMS_ROOT/src/git/alias/git.alias.commit.sh"
GBW_PARAMS_GIT_ALIAS_STATUS_FILE="$GBW_PARAMS_ROOT/src/git/alias/git.alias.status.sh"

GBW_PARAMS_GIT_HOOKS_DIR="$GBW_PARAMS_ROOT/git/hooks/"

GBW_PARAMS_GIT_REMOTE_BRANCH_REF=""


