#!/usr/bin/env bash

GBW_PARAMS_TEST_FAKE_USER_PS1="user"
GBW_PARAMS_TEST_FAKE_CURRENT_BRANCH="current-branch"
GBW_PARAMS_TEST_FAKE_GIT_REMOTE_BRANCH_REF="remote-branch"
GBW_PARAMS_TEST_FAKE_GIT_REMOTE_BRANCH_REF_NOK="nok-branch"

GBW_PARAMS_TEST_GIT_GET_CURRENT_BRANCH="current-branch"
GBW_PARAMS_TEST_GIT_GET_REMOTE_BRANCH_REF="remote-branch"

GBW_PARAMS_TEST_ASSERT_OK_SHOW_MESSAGE=0
