#!/usr/bin/env bash

GBW_PARAMS_TEST_PROMPT_TIME="\e[91m\t\e[0m"

GBW_PARAMS_TEST_PROMPT_USER="\e[92m$_GBW_FAKE_USER\e[0m"
GBW_PARAMS_TEST_PROMPT_HOST="\e[92m\h\e[0m"
GBW_PARAMS_TEST_PROMPT_USERHOST_GLUE="\e[92m@\e[0m"
GBW_PARAMS_TEST_PROMPT_USERHOST="${GBW_PARAMS_TEST_PROMPT_USER}${GBW_PARAMS_TEST_PROMPT_USERHOST_GLUE}${GBW_PARAMS_TEST_PROMPT_HOST}"

GBW_PARAMS_TEST_PROMPT_DIR="\e[36m\w\e[0m"
GBW_PARAMS_TEST_PROMPT_BRANCH="\e[93m($_GBW_FAKE_CURRENT_BRANCH)\e[0m"
GBW_PARAMS_TEST_PROMPT_COUNT="\e[95m11≡\e[0m"

GBW_PARAMS_TEST_PROMPT_STATUS_C="\e[92mc(3 +1 -1)\e[0m"
GBW_PARAMS_TEST_PROMPT_STATUS_S="\e[91m5!\e[0m"
GBW_PARAMS_TEST_PROMPT_STATUS_U="\e[91m1?\e[0m"
GBW_PARAMS_TEST_PROMPT_STATUS="$GBW_PARAMS_TEST_PROMPT_STATUS_U $GBW_PARAMS_TEST_PROMPT_STATUS_S $GBW_PARAMS_TEST_PROMPT_STATUS_C"

GBW_PARAMS_TEST_PROMPT_BEHIND="\e[37m0↓\e[0m"
GBW_PARAMS_TEST_PROMPT_BEHIND_NOK="\e[91mx↓\e[0m"
GBW_PARAMS_TEST_PROMPT_AHEAD="\e[37m88↑\e[0m"
GBW_PARAMS_TEST_PROMPT_AHEAD_NOK="\e[91mx↑\e[0m"

GBW_PARAMS_TEST_PROMPT_PS1_PART1="$GBW_PARAMS_TEST_PROMPT_TIME $GBW_PARAMS_TEST_PROMPT_USERHOST:$GBW_PARAMS_TEST_PROMPT_DIR $GBW_PARAMS_TEST_PROMPT_BRANCH $GBW_PARAMS_TEST_PROMPT_COUNT $GBW_PARAMS_TEST_PROMPT_STATUS $GBW_PARAMS_TEST_PROMPT_BEHIND $GBW_PARAMS_TEST_PROMPT_AHEAD"
GBW_PARAMS_TEST_PROMPT_PS1_PART2="\e[0m\n$ "