#!/usr/bin/env bash

TEST_GBW_PARAMS_PROMPT_TIME="\e[91m\t\e[0m"

TEST_GBW_PARAMS_PROMPT_USER="\e[92m${TEST_GBW_PARAMS_FAKE_USER_PS}1\e[0m"
TEST_GBW_PARAMS_PROMPT_HOST="\e[92m\h\e[0m"
TEST_GBW_PARAMS_PROMPT_USERHOST_GLUE="\e[92m@\e[0m"
TEST_GBW_PARAMS_PROMPT_USERHOST="${TEST_GBW_PARAMS_PROMPT_USER}${TEST_GBW_PARAMS_PROMPT_USERHOST_GLUE}${TEST_GBW_PARAMS_PROMPT_HOST}"

TEST_GBW_PARAMS_PROMPT_DIR="\e[36m\w\e[0m"
TEST_GBW_PARAMS_PROMPT_BRANCH="\e[93m(${TEST_GBW_PARAMS_FAKE_CURRENT_BRANCH})\e[0m"
TEST_GBW_PARAMS_PROMPT_COUNT="\e[95m11≡\e[0m"

TEST_GBW_PARAMS_PROMPT_STATUS_C="\e[92mc(3 +1 -1)\e[0m"
TEST_GBW_PARAMS_PROMPT_STATUS_S="\e[91m5!\e[0m"
TEST_GBW_PARAMS_PROMPT_STATUS_U="\e[91m1?\e[0m"
TEST_GBW_PARAMS_PROMPT_STATUS="${TEST_GBW_PARAMS_PROMPT_STATUS_U} ${TEST_GBW_PARAMS_PROMPT_STATUS_S} ${TEST_GBW_PARAMS_PROMPT_STATUS_C}"

TEST_GBW_PARAMS_PROMPT_BEHIND="\e[37m0↓\e[0m"
TEST_GBW_PARAMS_PROMPT_BEHIND_NOK="\e[91mx↓\e[0m"
TEST_GBW_PARAMS_PROMPT_AHEAD="\e[37m88↑\e[0m"
TEST_GBW_PARAMS_PROMPT_AHEAD_NOK="\e[91mx↑\e[0m"

TEST_GBW_PARAMS_PROMPT_PS1_PART1="${TEST_GBW_PARAMS_PROMPT_TIME} ${TEST_GBW_PARAMS_PROMPT_USERHOST}:${TEST_GBW_PARAMS_PROMPT_DIR} ${TEST_GBW_PARAMS_PROMPT_BRANCH} ${TEST_GBW_PARAMS_PROMPT_COUNT} ${TEST_GBW_PARAMS_PROMPT_STATUS} ${TEST_GBW_PARAMS_PROMPT_BEHIND} ${TEST_GBW_PARAMS_PROMPT_AHEAD}"
TEST_GBW_PARAMS_PROMPT_PS1_PART2="\e[0m\n$ "