#!/usr/bin/env bash

_GBW_FAKE_USER="user"
_GBW_FAKE_CURRENT_BRANCH="current-branch"
_GBW_FAKE_REMOTE_BRANCH_REF="remote-branch"
_GBW_FAKE_REMOTE_BRANCH_REF_NOK="nok-branch"

GBW_USER_PS1="$_GBW_FAKE_USER"
GBW_GIT_REMOTE_BRANCH_REF="$_GBW_FAKE_REMOTE_BRANCH_REF"

_TEST_GBW_GIT_GET_CURRENT_BRANCH="current-branch"
_TEST_GBW_GIT_GET_REMOTE_BRANCH_REF="remote-branch"