#!/usr/bin/env bash

GBW_PARAMS_USER_PS1="${TEST_GBW_PARAMS_FAKE_USER_PS}1"
GBW_PARAMS_GIT_REMOTE_BRANCH_REF="${TEST_GBW_PARAMS_FAKE_GIT_REMOTE_BRANCH_REF}"

GBW_PARAMS_INSTALL_PROMPT_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_GIT_ALIASES_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_GIT_HOOKS_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_WORKFLOW_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_BASH_ALIASES_STATUS="${GBW_PARAMS_ENABLED}"

GBW_PARAMS_PRINT_E_TAG=""
