#!/usr/bin/env bash
# shellcheck disable=SC2034
:

TEST_GX_PARAMS_FALSE="false"
TEST_GX_PARAMS_TRUE="true"

TEST_GX_PARAMS_TAB="    "
TEST_GX_PARAMS_TAB_2="${TEST_GX_PARAMS_TAB}${TEST_GX_PARAMS_TAB}"

TEST_GX_PARAMS_FAKE_USER_PS1="user"
TEST_GX_PARAMS_FAKE_CURRENT_USERNAME="current-username"
TEST_GX_PARAMS_FAKE_CURRENT_BRANCH="current-branch"

TEST_GX_PARAMS_FAKE_GIT_REMOTE_BRANCH_REF="remote-branch"
TEST_GX_PARAMS_FAKE_GIT_REMOTE_BRANCH_REF_NOK="wrong-remote-branch"

TEST_GX_PARAMS_ASSERT_OK_SHOW_MESSAGE=0
