#!/usr/bin/env bash
# shellcheck disable=SC2034
:

TEST_F_BOLD="\e[1m";
TEST_F_DIM="\e[2m";
TEST_F_UNDERLINED="\e[4m";
TEST_F_INVERTED="\e[7m";
TEST_F_HIDDEN="\e[8m"
TEST_F_RESET="\e[0m"

TEST_C_DEFAULT="\e[39m"
TEST_C_BLACK="\e[30m"
TEST_C_RED="\e[31m"
TEST_C_GREEN="\e[32m"
TEST_C_YELLOW="\e[33m"
TEST_C_BLUE="\e[34m"
TEST_C_MAGENTA="\e[35m"
TEST_C_CYAN="\e[36m"
TEST_C_LIGHT_GRAY="\e[37m"
TEST_C_DARK_GRAY="\e[90m"
TEST_C_LIGHT_RED="\e[91m"
TEST_C_LIGHT_GREEN="\e[92m"
TEST_C_LIGHT_YELLOW="\e[93m"
TEST_C_LIGHT_BLUE="\e[94m"
TEST_C_LIGHT_MAGENTA="\e[95m"
TEST_C_LIGHT_CYAN="\e[96m"
TEST_C_WHITE="\e[97m"

TEST_C_BG_DEFAULT="\e[49m"
TEST_C_BG_BLACK="\e[40m"
TEST_C_BG_RED="\e[41m"
TEST_C_BG_GREEN="\e[42m"
TEST_C_BG_YELLOW="\e[43m"
TEST_C_BG_BLUE="\e[44m"
TEST_C_BG_MAGENTA="\e[45m"
TEST_C_BG_CYAN="\e[46m"
TEST_C_BG_LIGHT_GRAY="\e[47m"
TEST_C_BG_DARK_GRAY="\e[100m"
TEST_C_BG_LIGHT_RED="\e[101m"
TEST_C_BG_LIGHT_GREEN="\e[102m"
TEST_C_BG_LIGHT_YELLOW="\e[103m"
TEST_C_BG_LIGHT_BLUE="\e[104m"
TEST_C_BG_LIGHT_MAGENTA="\e[105m"
TEST_C_BG_LIGHT_CYAN="\e[106m"
TEST_C_BG_WHITE="\e[107m"