#!/usr/bin/env bash
# shellcheck disable=SC2034
:

GX_PARAMS_USER_PS1="${TEST_GX_PARAMS_FAKE_USER_PS}1"
GX_PARAMS_INSTALL_PROMPT_STATUS="${GX_PARAMS_ENABLED}"
GX_PARAMS_INSTALL_GIT_ALIASES_STATUS="${GX_PARAMS_ENABLED}"
#GX_PARAMS_INSTALL_GIT_HOOKS_STATUS="${GX_PARAMS_ENABLED}"
#GX_PARAMS_INSTALL_WORKFLOW_STATUS="${GX_PARAMS_ENABLED}"
#GX_PARAMS_INSTALL_BASH_ALIASES_STATUS="${GX_PARAMS_ENABLED}"

GX_PARAMS_PRINT_E_TAG=""
