#!/usr/bin/env bash
# shellcheck disable=SC2034
:

TEST_GX_PARAMS_PROMPT_TIME="${TEST_C_LIGHT_RED}\t${TEST_F_RESET}"

TEST_GX_PARAMS_PROMPT_USER="${TEST_C_LIGHT_GREEN}${TEST_GX_PARAMS_FAKE_USER_PS}1${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_HOST="${TEST_C_LIGHT_GREEN}\h${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_USERHOST_GLUE="${TEST_C_LIGHT_GREEN}@${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_USERHOST="${TEST_GX_PARAMS_PROMPT_USER}${TEST_GX_PARAMS_PROMPT_USERHOST_GLUE}${TEST_GX_PARAMS_PROMPT_HOST}"

TEST_GX_PARAMS_PROMPT_DIR="${TEST_C_CYAN}\w${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_USERNAME="${TEST_C_LIGHT_YELLOW}(${TEST_GX_PARAMS_FAKE_CURRENT_USERNAME})${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_BRANCH="${TEST_C_LIGHT_YELLOW}(${TEST_GX_PARAMS_FAKE_CURRENT_BRANCH})${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_COUNT="${TEST_C_LIGHT_MAGENTA}11≡${TEST_F_RESET}"

TEST_GX_PARAMS_PROMPT_STATUS_C="${TEST_C_LIGHT_GREEN}c(3 +1 -1)${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_STATUS_S="${TEST_C_LIGHT_RED}5!${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_STATUS_U="${TEST_C_LIGHT_RED}1?${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_STATUS="${TEST_GX_PARAMS_PROMPT_STATUS_U} ${TEST_GX_PARAMS_PROMPT_STATUS_S} ${TEST_GX_PARAMS_PROMPT_STATUS_C}"

TEST_GX_PARAMS_PROMPT_BEHIND="${TEST_C_LIGHT_GRAY}0↓${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_BEHIND_NOK="${TEST_C_LIGHT_RED}x↓${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_AHEAD="${TEST_C_LIGHT_GRAY}88↑${TEST_F_RESET}"
TEST_GX_PARAMS_PROMPT_AHEAD_NOK="${TEST_C_LIGHT_RED}x↑${TEST_F_RESET}"

TEST_GX_PARAMS_PROMPT_PS1_PART1="${TEST_GX_PARAMS_PROMPT_TIME} ${TEST_GX_PARAMS_PROMPT_USERHOST}:${TEST_GX_PARAMS_PROMPT_DIR} ${TEST_GX_PARAMS_PROMPT_BRANCH} ${TEST_GX_PARAMS_PROMPT_COUNT} ${TEST_GX_PARAMS_PROMPT_STATUS} ${TEST_GX_PARAMS_PROMPT_BEHIND} ${TEST_GX_PARAMS_PROMPT_AHEAD}"
TEST_GX_PARAMS_PROMPT_PS1_PART2="${TEST_F_RESET}\n$ "