#!/usr/bin/env bash

TEST_GBW_PARAMS_TAB="    "
TEST_GBW_PARAMS_TAB_2="${TEST_GBW_PARAMS_TAB}${TEST_GBW_PARAMS_TAB}"

TEST_GBW_PARAMS_FAKE_USER_PS1="user"
TEST_GBW_PARAMS_FAKE_CURRENT_BRANCH="current-branch"

TEST_GBW_PARAMS_FAKE_GIT_REMOTE_BRANCH_REF="remote-branch"
TEST_GBW_PARAMS_FAKE_GIT_REMOTE_BRANCH_REF_NOK="nok-branch"

TEST_GBW_PARAMS_FAKE_GIT_GET_CURRENT_BRANCH="current-branch"
TEST_GBW_PARAMS_FAKE_GIT_GET_REMOTE_BRANCH_REF="remote-branch"

TEST_GBW_PARAMS_ASSERT_OK_SHOW_MESSAGE=0
