#!/usr/bin/env bash

_PROMPT_TIME="$C_LIGHT_RED\t"
_PROMPT_USER="$C_LIGHT_GREEN$USER@"
_PROMPT_HOST="$C_LIGHT_CYAN\h"
_PROMPT_LOCATION="$C_LIGHT_BLUE$(get_current_working_dir)"
_PROMPT_BRANCH="$C_LIGHT_YELLOW($(get_current_git_branch))"
_PROMPT_END="$F_RESET\n\$ "

PS1="$_PROMPT_TIME $_PROMPT_USER$_PROMPT_HOST $_PROMPT_LOCATION $_PROMPT_BRANCH$_PROMPT_END"
PS2="\[\033[01;36m\]>"

