#!/usr/bin/env bash

_GBW_FAKE_USER="user"
_GBW_FAKE_CURRENT_BRANCH="current-branch"
_GBW_FAKE_REMOTE_BRANCH_REF="remote-branch"
_GBW_FAKE_REMOTE_BRANCH_REF_NOK="nok-branch"

GBW_USER="$_GBW_FAKE_USER"
GBW_GIT_REMOTE_BRANCH_REF="$_GBW_FAKE_REMOTE_BRANCH_REF"

TEST_GBW_PROMPT_TIME="\e[91m\t\e[0m"
TEST_GBW_PROMPT_USER="\e[92muser\e[0m"
TEST_GBW_PROMPT_HOST="\e[96m\h\e[0m"
TEST_GBW_PROMPT_USERHOST="${TEST_GBW_PROMPT_USER}@${TEST_GBW_PROMPT_HOST}"
TEST_GBW_PROMPT_USERHOST_ESCAPE_AT="$TEST_GBW_PROMPT_USER\"@\"$TEST_GBW_PROMPT_HOST"
TEST_GBW_PROMPT_DIR="\e[94m\w\e[0m"
TEST_GBW_PROMPT_BRANCH="\e[93mcurrent-branch\e[0m"
TEST_GBW_PROMPT_COUNT="\e[93m(11)\e[0m"
TEST_GBW_PROMPT_STATUS_C="\e[92mc(\e[0m\e[92m3 \e[92m+1 \e[92m-1\e[0m\e[92m)\e[0m"
TEST_GBW_PROMPT_STATUS_S="\e[91m5!\e[0m"
TEST_GBW_PROMPT_STATUS_U="\e[91m1?\e[0m"
TEST_GBW_PROMPT_STATUS="$TEST_GBW_PROMPT_STATUS_U $TEST_GBW_PROMPT_STATUS_S $TEST_GBW_PROMPT_STATUS_C"
TEST_GBW_PROMPT_BEHIND="\e[37m0↓\e[0m"
TEST_GBW_PROMPT_BEHIND_NOK="\e[91mx↓\e[0m"
TEST_GBW_PROMPT_AHEAD="\e[37m88↑\e[0m"
TEST_GBW_PROMPT_AHEAD_NOK="\e[91mx↑\e[0m"

TEST_GBW_PROMPT_PS1_PART1="$TEST_GBW_PROMPT_TIME $TEST_GBW_PROMPT_USERHOST:$TEST_GBW_PROMPT_DIR $TEST_GBW_PROMPT_BRANCH $TEST_GBW_PROMPT_COUNT $TEST_GBW_PROMPT_STATUS $TEST_GBW_PROMPT_BEHIND $TEST_GBW_PROMPT_AHEAD"
TEST_GBW_PROMPT_PS1_PART2="\e[0m\n$ "