#!/usr/bin/env bash

GBW_PARAMS_GIT_CONFIG_KEY_ROOT="gx"

GBW_PARAMS_GIT_CONFIG_KEY_PROMPT="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.prompt"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.gitaliases"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.githooks"
GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.workflow"
GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.bashaliases"

GBW_PARAMS_GIT_CONFIG_KEY_PROMPT_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_PROMPT}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_TYPE="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.type"
GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW}.status"
GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES}.status"

GBW_PARAMS_GIT_ALIAS_DIFF_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.diff.sh"
GBW_PARAMS_GIT_ALIAS_COMMIT_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.commit.sh"
GBW_PARAMS_GIT_ALIAS_STATUS_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.status.sh"
GBW_PARAMS_GIT_ALIAS_FIND_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.find.sh"
GBW_PARAMS_GIT_ALIAS_CHECKOUT_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.checkout.sh"
GBW_PARAMS_GIT_ALIAS_ADD_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.add.sh"

GBW_PARAMS_GIT_HOOKS_DIR="${GBW_PARAMS_ROOT}/git/hooks/"

GBW_PARAMS_GIT_HOOKS_TYPE_HOOKSPATH="hookspath"
GBW_PARAMS_GIT_HOOKS_TYPE_SYMLINK="symlink"

GBW_PARAMS_GIT_REMOTE_BRANCH_REF=""

GBW_PARAMS_GIT_HOOKSPATH_VERSION_MIN="2.9.0"

GBW_PARAMS_GIT_ALIAS_L="l"
GBW_PARAMS_GIT_ALIAS_LL="ll"
GBW_PARAMS_GIT_ALIAS_LFILE="lfile"
GBW_PARAMS_GIT_ALIAS_LMERGES="lmerges"
GBW_PARAMS_GIT_ALIAS_LCOUNT="lcount"
GBW_PARAMS_GIT_ALIAS_B="b"
GBW_PARAMS_GIT_ALIAS_CK="ck"
GBW_PARAMS_GIT_ALIAS_S="s"
GBW_PARAMS_GIT_ALIAS_SS="ss"
GBW_PARAMS_GIT_ALIAS_D="d"
GBW_PARAMS_GIT_ALIAS_A="a"
GBW_PARAMS_GIT_ALIAS_ALL="all"
GBW_PARAMS_GIT_ALIAS_NM="nm"
GBW_PARAMS_GIT_ALIAS_MD="md"
GBW_PARAMS_GIT_ALIAS_C="c"
GBW_PARAMS_GIT_ALIAS_AMEND="amend"
GBW_PARAMS_GIT_ALIAS_R="r"
GBW_PARAMS_GIT_ALIAS_HARD="hard"
GBW_PARAMS_GIT_ALIAS_UNDO="undo"
GBW_PARAMS_GIT_ALIAS_UNTRACKED="untracked"
GBW_PARAMS_GIT_ALIAS_FIND="find"