#!/usr/bin/env bash

GBW_PARAMS_INSTALL_PROMPT_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_GIT_ALIASES_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_GIT_HOOKS_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_WORKFLOW_STATUS="${GBW_PARAMS_ENABLED}"
GBW_PARAMS_INSTALL_BASH_ALIASES_STATUS="${GBW_PARAMS_ENABLED}"

