#!/usr/bin/env bash

GX_PARAMS_INSTALL_PROMPT_STATUS="${GX_PARAMS_ENABLED}"
GX_PARAMS_INSTALL_GIT_ALIASES_STATUS="${GX_PARAMS_ENABLED}"
GX_PARAMS_INSTALL_GIT_HOOKS_STATUS="${GX_PARAMS_ENABLED}"
GX_PARAMS_INSTALL_WORKFLOW_STATUS="${GX_PARAMS_ENABLED}"
GX_PARAMS_INSTALL_BASH_ALIASES_STATUS="${GX_PARAMS_ENABLED}"

