#!/usr/bin/env bash
# shellcheck disable=SC2034
:

GX_PARAMS_GIT_CONFIG_KEY_ROOT="gx"

#GX_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.githooks"
#GX_PARAMS_GIT_CONFIG_KEY_WORKFLOW="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.workflow"
#GX_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.bashaliases"

GX_PARAMS_GIT_CONFIG_KEY_PROMPT_STATUS="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.prompt-status"
GX_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES_STATUS="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.gitaliases-status"
GX_PARAMS_GIT_CONFIG_KEY_GIT_REMOTE_BRANCH_REF="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.remote-branch-ref"
GX_PARAMS_GIT_CONFIG_KEY_GIT_COMMIT_LAST_SCOPE="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.commit-last-main"
GX_PARAMS_GIT_CONFIG_KEY_GIT_COMMIT_LAST_REFERENCE="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.commit-last-reference"
GX_PARAMS_GIT_CONFIG_KEY_GIT_COMMIT_LAST_TYPE_INDEX="${GX_PARAMS_GIT_CONFIG_KEY_ROOT}.commit-last-type"
#GX_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_STATUS="${GX_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.status"
#GX_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_TYPE="${GX_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.type"
#GX_PARAMS_GIT_CONFIG_KEY_WORKFLOW_STATUS="${GX_PARAMS_GIT_CONFIG_KEY_WORKFLOW}.status"
#GX_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES_STATUS="${GX_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES}.status"

GX_PARAMS_GIT_ALIAS_DIFF_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.diff.sh"
GX_PARAMS_GIT_ALIAS_COMMIT_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.commit.sh"
GX_PARAMS_GIT_ALIAS_STATUS_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.status.sh"
GX_PARAMS_GIT_ALIAS_FIND_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.find.sh"
GX_PARAMS_GIT_ALIAS_CHECKOUT_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.checkout.sh"
GX_PARAMS_GIT_ALIAS_ADD_FILE="${GX_PARAMS_ROOT}/src/git/alias/git.alias.add.sh"

#GX_PARAMS_GIT_HOOKS_DIR="${GX_PARAMS_ROOT}/git/hooks/"

#GX_PARAMS_GIT_HOOKS_TYPE_HOOKSPATH="hookspath"
#GX_PARAMS_GIT_HOOKS_TYPE_SYMLINK="symlink"

GX_PARAMS_GIT_HOOKSPATH_VERSION_MIN="2.9.0"

GX_PARAMS_GIT_ALIAS_L="l"
GX_PARAMS_GIT_ALIAS_LL="ll"
GX_PARAMS_GIT_ALIAS_LFILE="lfile"
GX_PARAMS_GIT_ALIAS_LMERGES="lmerges"
GX_PARAMS_GIT_ALIAS_LCOUNT="lcount"
GX_PARAMS_GIT_ALIAS_B="b"
GX_PARAMS_GIT_ALIAS_CANCEL="cancel"
GX_PARAMS_GIT_ALIAS_S="s"
GX_PARAMS_GIT_ALIAS_SS="ss"
GX_PARAMS_GIT_ALIAS_D="d"
GX_PARAMS_GIT_ALIAS_A="a"
GX_PARAMS_GIT_ALIAS_ALL="all"
GX_PARAMS_GIT_ALIAS_NM="nm"
GX_PARAMS_GIT_ALIAS_MD="md"
GX_PARAMS_GIT_ALIAS_C="c"
GX_PARAMS_GIT_ALIAS_AMEND="amend"
GX_PARAMS_GIT_ALIAS_R="r"
GX_PARAMS_GIT_ALIAS_HARD="hard"
GX_PARAMS_GIT_ALIAS_UNDO="undo"
GX_PARAMS_GIT_ALIAS_UNTRACKED="untracked"
GX_PARAMS_GIT_ALIAS_FIND="find"
