#!/usr/bin/env bash
# shellcheck disable=SC2034
:

GX_PARAMS_PROMPT_TIME_COLORS=${C_LIGHT_RED}
GX_PARAMS_PROMPT_USER_COLORS=${C_LIGHT_GREEN}
GX_PARAMS_PROMPT_HOST_COLORS=${C_LIGHT_GREEN}
GX_PARAMS_PROMPT_USERHOST_COLORS=${C_LIGHT_GREEN}
GX_PARAMS_PROMPT_DIR_COLORS=${C_LIGHT_MAGENTA}

GX_PARAMS_PROMPT_USERNAME_COLORS=${C_CYAN}
GX_PARAMS_PROMPT_BRANCH_COLORS=${C_LIGHT_YELLOW}

GX_PARAMS_PROMPT_CHANGES_COUNT_COLORS=${C_LIGHT_MAGENTA}
GX_PARAMS_PROMPT_STATUS_TO_BE_COMMITED_COLORS_ON=${C_LIGHT_GREEN}
GX_PARAMS_PROMPT_STATUS_TO_BE_COMMITED_COLORS_OFF=${C_DARK_GRAY}
GX_PARAMS_PROMPT_STATUS_NOT_STAGED_COLORS=${C_DARK_GRAY}
GX_PARAMS_PROMPT_STATUS_NOT_STAGED_COLORS_ERROR=${C_LIGHT_RED}
GX_PARAMS_PROMPT_STATUS_UNTRACKED_COLORS=${C_DARK_GRAY}
GX_PARAMS_PROMPT_STATUS_UNTRACKED_COLORS_ERROR=${C_LIGHT_RED}

GX_PARAMS_PROMPT_BEHIND_COLORS=${C_LIGHT_GRAY}
GX_PARAMS_PROMPT_BEHIND_COLORS_ERROR=${C_LIGHT_RED}
GX_PARAMS_PROMPT_AHEAD_COLORS=${C_LIGHT_GRAY}
GX_PARAMS_PROMPT_AHEAD_COLORS_ERROR=${C_LIGHT_RED}

GX_PARAMS_PROMPT_SET_PS2_COLORS=${C_CYAN}
