#!/usr/bin/env bash
# shellcheck disable=SC2034
:

GX_PARAMS_COMMANDS_GX="gx"

GX_PARAMS_COMMANDS_ACTION_ALIAS="alias" # !!! `aliases` does not work
GX_PARAMS_COMMANDS_ACTION_COMMANDS="commands"
GX_PARAMS_COMMANDS_ACTION_COLORS="colors"
GX_PARAMS_COMMANDS_ACTION_CONFIG="config"
GX_PARAMS_COMMANDS_ACTION_HELP="help"
GX_PARAMS_COMMANDS_ACTION_INSTALL="install"
GX_PARAMS_COMMANDS_ACTION_PROMPT="prompt"
GX_PARAMS_COMMANDS_ACTION_RELOAD="reload"
GX_PARAMS_COMMANDS_ACTION_STATUS="status"
GX_PARAMS_COMMANDS_ACTION_TEST="test"
