#!/usr/bin/env bash

GBW_PARAMS_GIT_CONFIG_KEY_ROOT="gbw"

GBW_PARAMS_GIT_CONFIG_KEY_PROMPT="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.prompt"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.gitaliases"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.githooks"
GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.workflow"
GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES="${GBW_PARAMS_GIT_CONFIG_KEY_ROOT}.bashaliases"

GBW_PARAMS_GIT_CONFIG_KEY_PROMPT_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_PROMPT}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_ALIASES}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.status"
GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS_TYPE="${GBW_PARAMS_GIT_CONFIG_KEY_GIT_HOOKS}.type"
GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_WORKFLOW}.status"
GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES_STATUS="${GBW_PARAMS_GIT_CONFIG_KEY_BASH_ALIASES}.status"

GBW_PARAMS_GIT_ALIAS_DIFF_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.diff.sh"
GBW_PARAMS_GIT_ALIAS_COMMIT_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.commit.sh"
GBW_PARAMS_GIT_ALIAS_STATUS_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.status.sh"
GBW_PARAMS_GIT_ALIAS_FIND_FILE="${GBW_PARAMS_ROOT}/src/git/alias/git.alias.find.sh"

GBW_PARAMS_GIT_HOOKS_DIR="${GBW_PARAMS_ROOT}/git/hooks/"

GBW_PARAMS_GIT_HOOKS_TYPE_HOOKSPATH="hookspath"
GBW_PARAMS_GIT_HOOKS_TYPE_SYMLINK="symlink"

GBW_PARAMS_GIT_REMOTE_BRANCH_REF=""

GBW_PARAMS_GIT_HOOKSPATH_VERSION_MIN="2.9.0"